version: '3.7'

services:

  iris: 
    image: intersystemsdc/irisdemo-demo-finrep:iris-version-1.0.8
    hostname: iris
    init: true
    container_name: iris
    ports:
    - "10000:52773" # 52773 is the webserver/management portal port: http://localhost:9092/csp/sys/UtilHome.csp
    volumes:
    - type: bind
      source: ./MortgageSystemFiles
      target: /MortgageSystemFiles
    - type: bind
      source: ./FCAGeneratedReports
      target: /FCAGeneratedReports
    - type: volume
      source: dur
      target: /dur
    cap_add:
      - IPC_LOCK
    security_opt:             # For a demo, this is ok and will provide for more performance. Maybe it is not necessary with privileged:true bellow
      - seccomp:unconfined
    privileged: true          # For a demo, this is ok and will provide for more performance.
