version: '3.7'

networks:
  mynetwork.com:
    external:
      name: net_test

services:

  iris:
    image: intersystemsdc/irisdemo-demo-finrep:iris-version-1.0.1
    hostname: iris
    init: true
    container_name: iris
    ports:
    - "10000:52773" # 52773 is the webserver/management portal port: http://localhost:9092/csp/sys/UtilHome.csp
    volumes:
    - type: bind
      source: ./MortgageSystemFiles
      target: /MortgageSystemFiles
    - type: bind
      source: ./FCAGeneratedReports
      target: /FCAGeneratedReports
    - type: bind
      source: ./hyperledger/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml
      target: /hyperledger/certs/connection-org1.yaml
    - type: bind
      source: ./hyperledger/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
      target: /hyperledger/certs/ca.org1.example.com-cert.pem
    - type: bind
      source: ./image-iris/hyperledger-wallet
      target: /hyperledger/wallet

    networks:
      - mynetwork.com
