Class Hyperledger.BO.CreateReportTransactionResp Extends Ens.Response [ Language = objectscript ]
{

Property ReportSaveStatus As %String;

Storage Default
{
<Data name="CreateReportTransactionRespDefaultData">
<Subscript>"CreateReportTransactionResp"</Subscript>
<Value name="1">
<Value>ReportSaveStatus</Value>
</Value>
</Data>
<DefaultData>CreateReportTransactionRespDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
