Class Canonical.CT.BorrowerType Extends CodeDescBase
{

Storage Default
{
<Data name="BorrowerTypeDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.BorrowerTypeD</DataLocation>
<DefaultData>BorrowerTypeDefaultData</DefaultData>
<IdLocation>^Canonical.CT.BorrowerTypeD</IdLocation>
<IndexLocation>^Canonical.CT.BorrowerTypeI</IndexLocation>
<StreamLocation>^Canonical.CT.BorrowerTypeS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
