Class Canonical.CT.BorrowerImpCredHist Extends CodeDescBase
{

Storage Default
{
<Data name="BorrowerImpCredHistDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.BorrowerImp690CD</DataLocation>
<DefaultData>BorrowerImpCredHistDefaultData</DefaultData>
<IdLocation>^Canonical.CT.BorrowerImp690CD</IdLocation>
<IndexLocation>^Canonical.CT.BorrowerImp690CI</IndexLocation>
<StreamLocation>^Canonical.CT.BorrowerImp690CS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
