Class Canonical.CT.HowSaleMade Extends CodeDescBase
{

Storage Default
{
<Data name="HowSaleMadeDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.HowSaleMadeD</DataLocation>
<DefaultData>HowSaleMadeDefaultData</DefaultData>
<IdLocation>^Canonical.CT.HowSaleMadeD</IdLocation>
<IndexLocation>^Canonical.CT.HowSaleMadeI</IndexLocation>
<StreamLocation>^Canonical.CT.HowSaleMadeS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
