Class Canonical.CT.IncomeBasis Extends CodeDescBase
{

Storage Default
{
<Data name="IncomeBasisDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.IncomeBasisD</DataLocation>
<DefaultData>IncomeBasisDefaultData</DefaultData>
<IdLocation>^Canonical.CT.IncomeBasisD</IdLocation>
<IndexLocation>^Canonical.CT.IncomeBasisI</IndexLocation>
<StreamLocation>^Canonical.CT.IncomeBasisS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
