Class Canonical.CT.IncomeVerification Extends CodeDescBase
{

Storage Default
{
<Data name="IncomeVerificationDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.IncomeVerifD3C6D</DataLocation>
<DefaultData>IncomeVerificationDefaultData</DefaultData>
<IdLocation>^Canonical.CT.IncomeVerifD3C6D</IdLocation>
<IndexLocation>^Canonical.CT.IncomeVerifD3C6I</IndexLocation>
<StreamLocation>^Canonical.CT.IncomeVerifD3C6S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
