Class Canonical.CT.MainEmpStatus Extends CodeDescBase
{

Storage Default
{
<Data name="MainEmpStatusDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.MainEmpStatusD</DataLocation>
<DefaultData>MainEmpStatusDefaultData</DefaultData>
<IdLocation>^Canonical.CT.MainEmpStatusD</IdLocation>
<IndexLocation>^Canonical.CT.MainEmpStatusI</IndexLocation>
<StreamLocation>^Canonical.CT.MainEmpStatusS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
