Class Canonical.CT.MCOBUsed Extends CodeDescBase
{

Storage Default
{
<Data name="MCOBUsedDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.MCOBUsedD</DataLocation>
<DefaultData>MCOBUsedDefaultData</DefaultData>
<IdLocation>^Canonical.CT.MCOBUsedD</IdLocation>
<IndexLocation>^Canonical.CT.MCOBUsedI</IndexLocation>
<StreamLocation>^Canonical.CT.MCOBUsedS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
