Class Canonical.CT.MtgeType Extends CodeDescBase
{

Storage Default
{
<Data name="MtgeTypeDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.MtgeTypeD</DataLocation>
<DefaultData>MtgeTypeDefaultData</DefaultData>
<IdLocation>^Canonical.CT.MtgeTypeD</IdLocation>
<IndexLocation>^Canonical.CT.MtgeTypeI</IndexLocation>
<StreamLocation>^Canonical.CT.MtgeTypeS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
