Class Canonical.CT.MtgeChar Extends CodeDescBase
{

Storage Default
{
<Data name="MtgeCharDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.MtgeCharD</DataLocation>
<DefaultData>MtgeCharDefaultData</DefaultData>
<IdLocation>^Canonical.CT.MtgeCharD</IdLocation>
<IndexLocation>^Canonical.CT.MtgeCharI</IndexLocation>
<StreamLocation>^Canonical.CT.MtgeCharS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
