Class Canonical.CT.ReasonForClosure Extends CodeDescBase
{

Storage Default
{
<Data name="ReasonForClosureDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.ReasonForClosureD</DataLocation>
<DefaultData>ReasonForClosureDefaultData</DefaultData>
<IdLocation>^Canonical.CT.ReasonForClosureD</IdLocation>
<IndexLocation>^Canonical.CT.ReasonForClosureI</IndexLocation>
<StreamLocation>^Canonical.CT.ReasonForClosureS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
