Class Canonical.CT.RemtgePurpose Extends CodeDescBase
{

Storage Default
{
<Data name="RemtgePurposeDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.RemtgePurposeD</DataLocation>
<DefaultData>RemtgePurposeDefaultData</DefaultData>
<IdLocation>^Canonical.CT.RemtgePurposeD</IdLocation>
<IndexLocation>^Canonical.CT.RemtgePurposeI</IndexLocation>
<StreamLocation>^Canonical.CT.RemtgePurposeS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
