Class Canonical.CT.RepaymentStrategy Extends CodeDescBase
{

Storage Default
{
<Data name="RepaymentStrategyDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.RepaymentStA855D</DataLocation>
<DefaultData>RepaymentStrategyDefaultData</DefaultData>
<IdLocation>^Canonical.CT.RepaymentStA855D</IdLocation>
<IndexLocation>^Canonical.CT.RepaymentStA855I</IndexLocation>
<StreamLocation>^Canonical.CT.RepaymentStA855S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
