Class Canonical.CT.RepayMethod Extends CodeDescBase
{

Storage Default
{
<Data name="RepayMethodDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.RepayMethodD</DataLocation>
<DefaultData>RepayMethodDefaultData</DefaultData>
<IdLocation>^Canonical.CT.RepayMethodD</IdLocation>
<IndexLocation>^Canonical.CT.RepayMethodI</IndexLocation>
<StreamLocation>^Canonical.CT.RepayMethodS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
