Class Canonical.CT.TypeDwelling Extends CodeDescBase
{

Storage Default
{
<Data name="TypeDwellingDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.TypeDwellingD</DataLocation>
<DefaultData>TypeDwellingDefaultData</DefaultData>
<IdLocation>^Canonical.CT.TypeDwellingD</IdLocation>
<IndexLocation>^Canonical.CT.TypeDwellingI</IndexLocation>
<StreamLocation>^Canonical.CT.TypeDwellingS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
