Class Canonical.CT.TypeReversionRate Extends CodeDescBase
{

Storage Default
{
<Data name="TypeReversionRateDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.TypeReversi14E0D</DataLocation>
<DefaultData>TypeReversionRateDefaultData</DefaultData>
<IdLocation>^Canonical.CT.TypeReversi14E0D</IdLocation>
<IndexLocation>^Canonical.CT.TypeReversi14E0I</IndexLocation>
<StreamLocation>^Canonical.CT.TypeReversi14E0S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
