Class Canonical.CT.TypeIntRate Extends CodeDescBase
{

Storage Default
{
<Data name="TypeIntRateDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.TypeIntRateD</DataLocation>
<DefaultData>TypeIntRateDefaultData</DefaultData>
<IdLocation>^Canonical.CT.TypeIntRateD</IdLocation>
<IndexLocation>^Canonical.CT.TypeIntRateI</IndexLocation>
<StreamLocation>^Canonical.CT.TypeIntRateS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
