Class Canonical.CT.ValuationType Extends CodeDescBase
{

Storage Default
{
<Data name="ValuationTypeDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^Canonical.CT.ValuationTypeD</DataLocation>
<DefaultData>ValuationTypeDefaultData</DefaultData>
<IdLocation>^Canonical.CT.ValuationTypeD</IdLocation>
<IndexLocation>^Canonical.CT.ValuationTypeI</IndexLocation>
<StreamLocation>^Canonical.CT.ValuationTypeS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
